version: '2'
services:

    # Application container
    php:
        build: .
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
        ports:
            - "8080:80"
        links:
            - mysql
            - redis
        environment:
            DEBUG: 'true'

    mysql:
        image: mysql:5.7
        restart: unless-stopped
        ports:
            - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: hellofresh
            MYSQL_USER: hellofresh
            MYSQL_PASSWORD: hellofresh

    redis:
        image: redis:alpine
        restart: unless-stopped
        ports:
            - "6379:6379"

